### PR TITLE
Ccl emu

### PR DESCRIPTION
**Pull request by jpratmarti**
Adding a feature to be able to set cosmology at the plotting script.

Also correcting Fourier space measurements with the beam correction. 

Also fixing a bug in twopoint which was crashing.

### CODE REVIEW

**Comment by jpratmarti** [comment]
I am not sure how to solve the failing check. @joezuntz any ideas?

**Comment by joezuntz** [comment]
Looks like it's failing in the theory calculation, an integration error in TXTwoPointPlots:

```
/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/sacc/sacc.py:370: UserWarning: Empty index selected - maybe you should check the tracer order?

  warnings.warn("Empty index selected - maybe you "

Traceback (most recent call last):

  File "/opt/python/3.7.6/lib/python3.7/runpy.py", line 193, in _run_module_as_main

    "__main__", mod_spec)

  File "/opt/python/3.7.6/lib/python3.7/runpy.py", line 85, in _run_code

    exec(code, run_globals)

  File "/home/travis/build/LSSTDESC/TXPipe/txpipe/__main__.py", line 5, in <module>

    PipelineStage.main()

  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/ceci/stage.py", line 269, in main

    stage.execute(args)

  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/ceci/stage.py", line 351, in execute

    stage.run()

  File "/home/travis/build/LSSTDESC/TXPipe/txpipe/twopoint.py", line 809, in run

    figures=figures, cosmo=cosmo, theory_labels=['Fiducial'])

  File "/home/travis/build/LSSTDESC/TXPipe/txpipe/plotting/correlations.py", line 142, in full_3x2pt_plots

    for (s, label) in zip(theory_sacc_data, theory_labels)]

  File "/home/travis/build/LSSTDESC/TXPipe/txpipe/plotting/correlations.py", line 142, in <listcomp>

    for (s, label) in zip(theory_sacc_data, theory_labels)]

  File "/home/travis/build/LSSTDESC/TXPipe/txpipe/plotting/correlations.py", line 388, in make_theory_plot_data

    cl = pyccl.angular_cl(cosmo, tracers[f'source_{i}'], tracers[f'source_{j}'], ell)

  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/pyccl/cls.py", line 98, in angular_cl

    check(status, cosmo=cosmo_in)

  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/pyccl/pyutils.py", line 48, in check

    raise CCLError("Error %s: %s" % (error_types[status], msg))

pyccl.errors.CCLError: Error CCL_ERROR_INTEG: ccl_cls.c: ccl_angular_cls_limber(); integration error
```

Might be a mismatched version in CCL if it works for you.  Could you have a look at the .travis.yml file and see if it's getting a new enough version?

**Comment by jpratmarti** [comment]
@joezuntz sorry for not replying to this until now. In the travis.yml I found the following, but I don't know if it's new enough..  

pip install git+git://github.com/LSSTDESC/CCL@a9c23144727768a91af76da0c727830e6f0ed784

**Comment by joezuntz** [comment]
Could you try merging in master and seeing see if it runs now? (may have changed now we're on github actions and there will be a new CCL version).

And have you tried all three variations (laptop_pipeline, laptop_redmagic_pipeline, and laptop_lensfit_pipeline) on your machine?

**Comment by joezuntz** [comment]
I meant to merge master into this branch - the you'll get the new github actions testing instead of travis.

**Comment by jpratmarti** [comment]
Done @joezuntz!

**Comment by jpratmarti** [comment]
Now I don't understand why TXTwoPointPlots is failing again.. I checked and it works on my machine. I only added the print statement, before it worked right? Is it a Travis problem?

**Comment by joezuntz** [comment]
Something went wrong in plotting/correlations.py - see the diff, looks like you have some stray line noise.

**Comment by jpratmarti** [comment]
ok did that, but now it is still giving the ccl integration error. I've checked and it's not breaking on my machine.

**Review by joezuntz — APPROVED** [review]

**Pull request merged**
