### PR TITLE
Add mock catalog type requiring no calibration, and add example pipeline

### PR DESCRIPTION
**Pull request by joezuntz**
Addresses issue #360 

Still looking at the ingestion part.

### CODE REVIEW

**Comment by ts485** [comment]
Hi Joe,

We also need an output "source_photoz_pdfs" (which is originally generated from the stage "BPZ_lite") to run the stage "CLClusterShearCatlog". Can either create one more stage or add the functionality to "TXSourceSelectorSimple" to generate "source_photoz_pdfs"?

I attached the flowchart of CL pipeline and the mock pipeline.

Best,
Tomomi
CL_pipeline
mock_pipeline

**Comment by joezuntz** [comment]
For speed, and to avoid difficult questions about photo-z for the source sample (which may have only r, i ,z), I have added a quick stage to generate fake source_photoz_pdfs using the true redshifts.  I've added it to the pipeline file.

I've also added a call to the CLClusterShearCatalogs stage. To use that as-is you will need to download and extract the latest version of the example.tar.gz inputs file.  See the README for the URL.

**Comment by ts485** [comment]
@joezuntz  Hi Joe, I am not sure what is changed now, but now "CLClusterShearCatalog" does not run properly and I think the problem is either shear or photos catalogs which have different file structure.

Log output is:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/conda/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/pscratch/sd/t/ts485/TXPipe_mock/txpipe/__main__.py", line 5, in <module>
    PipelineStage.main()
  File "/opt/conda/lib/python3.10/site-packages/ceci/stage.py", line 507, in main
    stage.execute(args)
  File "/opt/conda/lib/python3.10/site-packages/ceci/stage.py", line 659, in execute
    stage.run()
  File "/pscratch/sd/t/ts485/TXPipe_mock/txpipe/extensions/clmm/sources_select_compute.py", line 112, in run
    weights, tangential_comp, cross_comp = self.compute_sources_quantities(clmm_cosmo, data, gal_index, cluster_z,\
 cluster_ra, cluster_dec)
  File "/pscratch/sd/t/ts485/TXPipe_mock/txpipe/extensions/clmm/sources_select_compute.py", line 339, in compute_s\
ources_quantities
    weight = clmm.dataops.compute_galaxy_weights(
TypeError: compute_galaxy_weights() got multiple values for argument 'use_shape_noise'
Executing stage: CLClusterShearCatalogs @ 2024-07-23 22:25:39.176774
clmm version 1.12.5
Min search angle =  47.31632655959024 arcmin
Mean search angle =  47.31632655959024 arcmin
Max search angle =  47.31632655959024 arcmin
Max theta_max = 0.013763761473561509 radians = 47.31632655959024 arcmin
Using single 2D shear calibration!
Process 0 processing chunk 0 - 6,133
Stage failed: CLClusterShearCatalogs @ 2024-07-23 22:25:40.430158 after 0.02 minutes

**Comment by ts485** [comment]
P.S. I could run the pipeline till the end by using tx-10 instead of tx

**Pull request merged**
