### PR TITLE
Add fake map tool and theory support file

### PR DESCRIPTION
**Pull request by joezuntz**
Tool to generate fake maps for testing Fourier code

### CODE REVIEW

**Comment by chihway** [comment]
Looks good, only very small things:

sysmaps.py:
L306: do you actually use flask?? I think you mean healpix
L332: why only dec range?
L347: did this actually work? thought you need `from .utils.pixel_schemes import choose_pixelization`
L367: comments broken

theory.py:
L102: I think logspace is base 10 by default, so may want to specify or change to log10 in the limits
L593: comments broken

**Comment by joezuntz** [comment]
TODO List:

- [ ] L306: do you actually use flask?? I think you mean healpix
- [ ] L332: why only dec range?
- [ ] L347: did this actually work? thought you need from .utils.pixel_schemes import choose_pixelization
- [ ] L367: comments broken

theory.py:
- [ ] L102: I think logspace is base 10 by default, so may want to specify or change to log10 in the limits
- [ ] L593: comments broken

**Comment by joezuntz** [comment]
>  L347: did this actually work? thought you need from .utils.pixel_schemes import choose_pixelization

Yes, this works because in `utils/__init__.py` I import it from the module.

**Comment by joezuntz** [comment]
Okay, I've dealt with all these - many thanks!

**Pull request merged**
